#include "minemu/irq.h"
#include "minemu/platform.h"
#include "minemu/uart.h"

//generated by gpt6.1 sol

typedef void (*irq_handler_t)(void);

static void uart0_irq_handler(void); 

static irq_handler_t handlers[4] = {
    [MINEMU_IRQ_UART0] = uart0_irq_handler,
};

static void uart0_irq_handler(void) {
    uartInterrupt();
}

struct minemu_trap_frame *minemu_irq_dispatch(struct minemu_trap_frame *frame) {
    int32_t source = frame->exception_id;

    if (source >= 0 &&
        (size_t)source < sizeof(handlers) / sizeof(handlers[0]) &&
        handlers[source] != 0) {
        handlers[source]();  // Call the selected function.
    }

    MINEMU_INTERRUPT->eoi = (uint32_t)source;
    return frame;
};