//template generated by AI but modified by me for the msh (minimal shell) implementation

#include "minemu/msh.h"
#include "minemu/uart.h"
#include "minemu/printf.h"

void executeLine(char *line, unsigned int length) {
    /* Implement execution logic here. */
    //skip leading spaces
    unsigned int head = 0U;
    while ( head < length && line[head] == ' ') {
        ++head;
    }

    //base cases
    if (head == length) {
        return; 
    }

    unsigned int tail = head;
    //trying to find end of first work aka the command , and since we figured out leading spaces we jsut check til we reach another empty space.
    while (tail < length && line[tail] != ' ') {
        ++tail;
    }

    //check if its echo
    if (tail - head == 4U&&
        line[head] == 'e'&&
        line[head + 1] == 'c'&&
        line[head + 2] == 'h'&&
        line[head + 3] == 'o'
    ) {
        //we know we have echo cmd, just gotta figure out what to echo
        //gotta skip spaces after cmd
        unsigned int echoStart = tail;
        while (echoStart < length && line[echoStart] == ' ') {
            ++echoStart;
        }

        printf("%s\n", &line[echoStart]);
        return;

        // if (echoStart < length) {
        //     //print the rest of the line as the echo content
        //     printf("%s\n", &line[echoStart]);
        // }
    }
    //if its not echo
    else {
        // int notFoundStart = tail;
        // while (notFoundStart < length && line[notFoundStart] == ' ') {
        //     notFoundStart++;
        // }

        // if (notFoundStart < length) {
        //     //print the rest of the line as the echo content
        //     for (int i = notFoundStart; i < length; i++) {
        //         int word = notFoundStart[i];
        //         notFoundStart++;
        //     }
        // }
        line[tail] = '\0';
        printf("command not found: %s\n", &line[head]);
    }
}
void mshStart(void) {
    char line[21];             /* 20 bytes plus the terminating '\0' */
    unsigned int length = 0U;
    unsigned int excess = 0U;


    printf("msh> ");

    for (;;) {
        int value = uartReadByte();

        if (value == UART_NO_DATA) {
            continue;
        }

        if (value == UART_INPUT_LOST) {
            length = 0U;
            excess = 0U;
            line[0] = '\0';
            /* Reset any overlong-line state you add later. */
            printf("\ninput lost; line discarded\nmsh> ");
            continue;
        }

        if (value == '\n') {
            line[length] = '\0';

            if (excess != 0U) {
                printf("too long\n");
            } else {
                executeLine(line, length);
            }

            length = 0U;
            excess = 0U;
            printf("msh> ");
            continue;
        }

        //backspace
        if (value == 0x08 || value == 0x7F) {
            if (excess != 0U) {
                --excess;
            } else if (length != 0U) {
                --length;
                line[length] = '\0';
            }
            continue;
        }

        //if lines over 20 bytes

        if (length < 20U) {
            line[length] = (char)value;
            length++;
        } else {
            excess++;
        }
    }
}